[Window]
Name = "bezier-shading"
Width = 1100
Height = 600
FixedSize = true
Theme = "light"

[UI]
BackgroundColorRGBA = [0, 0, 0, 255]
SecondaryBackgroundColorRGBA = [82, 78, 183, 255]
RasterBorderColorRGBA = [0, 0, 0, 255]
RasterWidth = 600
RasterHeight = 600

[Defaults]
Kd = 0.5
Ks = 0.5
M = 1
LightColorRGBA = [255, 255, 255, 255]
LightAnimation = true
LightHeight = 200
DefaultBackgroundSolidColorRGBA = [255, 0, 0, 255]
Triangulation = 10
InterpolationPointsPerSide = 4

[Light]
SpiralMinRadius = 50
SpiralRadiusDelta = 0.1
SpiralAngleDelta = 0.005
SpiralUpdateMiliseconds = 10
